### ISSUE TITLE
Match the index to the correct camera device

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-miniscope#19]
![miniscope-correct-index](https://github.com/user-attachments/assets/c6030fdb-1fc5-4ed0-b4f7-3a5e618d3004)
![miniscope-incorrect-index](https://github.com/user-attachments/assets/c6e31756-82d1-438c-afff-41584ceec5a8)

**Comment by jonnew** [comment]
This seems to be a pretty fundamental issue. Both `OpenCV.CameraCapture`, which is used to talk to the miniscope the `IndexConverter` use DirectShow to create camera device enumerations. However, they are inexplicably in different orders between the `OpenCV` and `Aforge` libraries. There is no way that I can see for the OpenCV library to inspect the available DirectShow devices (which is why `Aforge` was used to create the list of available cameras). So we might have to remove this functionality.
